/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Davi
 */
public class TelaRecuperarInfo extends javax.swing.JInternalFrame {
    
    String tipo;

    /**
     * Creates new form TelaRecuperarInfo
     */
    public TelaRecuperarInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoRadioButton = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rbOpcao1 = new javax.swing.JRadioButton();
        rbOpcao2 = new javax.swing.JRadioButton();
        btEnviarRadioButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblResultadoRadioButton = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        checkBoxOpcao1 = new javax.swing.JCheckBox();
        checkBoxOpcao2 = new javax.swing.JCheckBox();
        btCheckBoxEnviar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblResultadoCheckBox = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cbProfessores = new javax.swing.JComboBox<>();
        btCaixaSelecaoEnviar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblResultadoCaixaSelecao = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        btListarEnviar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lblResultadoListar = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtCampo = new javax.swing.JTextField();
        btCaixaTextoEnviar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        lblResultadoCaixaTexto = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Radio Button"));

        grupoRadioButton.add(rbOpcao1);
        rbOpcao1.setText("Opcao1");
        rbOpcao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbOpcao1ActionPerformed(evt);
            }
        });

        grupoRadioButton.add(rbOpcao2);
        rbOpcao2.setText("Opcao2");
        rbOpcao2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbOpcao2ActionPerformed(evt);
            }
        });

        btEnviarRadioButton.setText("Enviar");
        btEnviarRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEnviarRadioButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Resultado:");

        lblResultadoRadioButton.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblResultadoRadioButton)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbOpcao1)
                        .addGap(18, 18, 18)
                        .addComponent(rbOpcao2))
                    .addComponent(btEnviarRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbOpcao1)
                    .addComponent(rbOpcao2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btEnviarRadioButton)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lblResultadoRadioButton)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("CheckBox"));

        checkBoxOpcao1.setText("Opcao1");

        checkBoxOpcao2.setText("Opcao2");

        btCheckBoxEnviar.setText("Enviar");
        btCheckBoxEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCheckBoxEnviarActionPerformed(evt);
            }
        });

        jLabel2.setText("Resultado:");

        lblResultadoCheckBox.setText("jLabel3");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btCheckBoxEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(checkBoxOpcao1)
                                .addGap(18, 18, 18)
                                .addComponent(checkBoxOpcao2))
                            .addComponent(jLabel2)
                            .addComponent(lblResultadoCheckBox))
                        .addContainerGap(23, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkBoxOpcao1)
                    .addComponent(checkBoxOpcao2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btCheckBoxEnviar)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(lblResultadoCheckBox)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Caixa de Seleção"));

        jLabel3.setText("Selecione:");

        cbProfessores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Davi", "Daniel", "Ricardo", "Rafael", "Rodrigo", "Lucas", "Henrique", "Jonas" }));

        btCaixaSelecaoEnviar.setText("Enviar");
        btCaixaSelecaoEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCaixaSelecaoEnviarActionPerformed(evt);
            }
        });

        jLabel4.setText("Resultado:");

        lblResultadoCaixaSelecao.setText("jLabel5");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btCaixaSelecaoEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbProfessores, 0, 181, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(lblResultadoCaixaSelecao))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbProfessores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btCaixaSelecaoEnviar)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(lblResultadoCaixaSelecao)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Listar"));

        list.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Davi", "Daniel", "Ricardo", "Rafael", "Rodrigo", "Lucas", "Henrique", "Jonas" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(list);

        jLabel5.setText("Selecione:");

        btListarEnviar.setText("Enviar");
        btListarEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListarEnviarActionPerformed(evt);
            }
        });

        jLabel6.setText("Resultado:");

        lblResultadoListar.setText("jLabel7");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btListarEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane1)))
                    .addComponent(jLabel6)
                    .addComponent(lblResultadoListar))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btListarEnviar)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(37, 37, 37)
                .addComponent(lblResultadoListar)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Caixa de Texto"));

        jLabel7.setText("Informe:");

        btCaixaTextoEnviar.setText("Enviar");
        btCaixaTextoEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCaixaTextoEnviarActionPerformed(evt);
            }
        });

        jLabel8.setText("Resultado:");

        lblResultadoCaixaTexto.setText("jLabel9");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btCaixaTextoEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCampo))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(lblResultadoCaixaTexto))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btCaixaTextoEnviar)
                .addGap(72, 72, 72)
                .addComponent(jLabel8)
                .addGap(37, 37, 37)
                .addComponent(lblResultadoCaixaTexto)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(93, Short.MAX_VALUE))
        );

        setBounds(0, 0, 877, 749);
    }// </editor-fold>//GEN-END:initComponents

    private void rbOpcao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbOpcao1ActionPerformed
        // TODO add your handling code here:
        tipo = "opcao1";
        
    }//GEN-LAST:event_rbOpcao1ActionPerformed

    private void rbOpcao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbOpcao2ActionPerformed
        // TODO add your handling code here:
        tipo = "opcao2";
    }//GEN-LAST:event_rbOpcao2ActionPerformed

    private void btEnviarRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEnviarRadioButtonActionPerformed
        // TODO add your handling code here:
        lblResultadoRadioButton.setText(tipo);
    }//GEN-LAST:event_btEnviarRadioButtonActionPerformed

    private void btCheckBoxEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCheckBoxEnviarActionPerformed
        // TODO add your handling code here:
        String opcao1="", opcao2="";
        
        if(checkBoxOpcao1.isSelected())
            opcao1 = "opcao1";
        if(checkBoxOpcao2.isSelected())
            opcao2 = "opcao2";
        
        lblResultadoCheckBox.setText(opcao1+" "+opcao2);
        
        
    }//GEN-LAST:event_btCheckBoxEnviarActionPerformed

    private void btCaixaSelecaoEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCaixaSelecaoEnviarActionPerformed
        // TODO add your handling code here:
        
        lblResultadoCaixaSelecao.setText(cbProfessores.getSelectedItem().toString());
    }//GEN-LAST:event_btCaixaSelecaoEnviarActionPerformed

    private void btListarEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListarEnviarActionPerformed
        // TODO add your handling code here:
        
        lblResultadoListar.setText(list.getSelectedValuesList()+"");
    }//GEN-LAST:event_btListarEnviarActionPerformed

    private void btCaixaTextoEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCaixaTextoEnviarActionPerformed
        // TODO add your handling code here:
        
        lblResultadoCaixaTexto.setText(txtCampo.getText());
    }//GEN-LAST:event_btCaixaTextoEnviarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCaixaSelecaoEnviar;
    private javax.swing.JButton btCaixaTextoEnviar;
    private javax.swing.JButton btCheckBoxEnviar;
    private javax.swing.JButton btEnviarRadioButton;
    private javax.swing.JButton btListarEnviar;
    private javax.swing.JComboBox<String> cbProfessores;
    private javax.swing.JCheckBox checkBoxOpcao1;
    private javax.swing.JCheckBox checkBoxOpcao2;
    private javax.swing.ButtonGroup grupoRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblResultadoCaixaSelecao;
    private javax.swing.JLabel lblResultadoCaixaTexto;
    private javax.swing.JLabel lblResultadoCheckBox;
    private javax.swing.JLabel lblResultadoListar;
    private javax.swing.JLabel lblResultadoRadioButton;
    private javax.swing.JList<String> list;
    private javax.swing.JRadioButton rbOpcao1;
    private javax.swing.JRadioButton rbOpcao2;
    private javax.swing.JTextField txtCampo;
    // End of variables declaration//GEN-END:variables
}
